"""initial migration

Revision ID: 122788c37ac0
Revises: 
Create Date: 2025-09-04 17:34:07.802001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '122788c37ac0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_created_at'), 'auditevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditevent_updated_at'), 'auditevent', ['updated_at'], unique=False)
    op.create_table('channel',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('recording_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_created_at'), 'channel', ['created_at'], unique=False)
    op.create_index(op.f('ix_channel_updated_at'), 'channel', ['updated_at'], unique=False)
    op.create_table('location',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_created_at'), 'location', ['created_at'], unique=False)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)
    op.create_index(op.f('ix_location_updated_at'), 'location', ['updated_at'], unique=False)
    op.create_table('mediaasset',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediaasset_created_at'), 'mediaasset', ['created_at'], unique=False)
    op.create_index(op.f('ix_mediaasset_updated_at'), 'mediaasset', ['updated_at'], unique=False)
    op.create_table('patient',
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('preferred_name', sa.String(length=200), nullable=True),
    sa.Column('primary_phone', sa.String(length=32), nullable=True),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_created_at'), 'patient', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_updated_at'), 'patient', ['updated_at'], unique=False)
    op.create_table('practitioner',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_created_at'), 'practitioner', ['created_at'], unique=False)
    op.create_index(op.f('ix_practitioner_name'), 'practitioner', ['name'], unique=False)
    op.create_index(op.f('ix_practitioner_updated_at'), 'practitioner', ['updated_at'], unique=False)
    op.create_table('routingrule',
    sa.Column('match', sa.JSON(), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routingrule_created_at'), 'routingrule', ['created_at'], unique=False)
    op.create_index(op.f('ix_routingrule_updated_at'), 'routingrule', ['updated_at'], unique=False)
    op.create_table('slapolicy',
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('category_filter', sa.String(length=32), nullable=True),
    sa.Column('priority_filter', sa.String(length=8), nullable=True),
    sa.Column('respond_within_minutes', sa.Integer(), nullable=False),
    sa.Column('resolve_within_minutes', sa.Integer(), nullable=False),
    sa.Column('pause_statuses', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slapolicy_created_at'), 'slapolicy', ['created_at'], unique=False)
    op.create_index(op.f('ix_slapolicy_updated_at'), 'slapolicy', ['updated_at'], unique=False)
    op.create_table('team',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_created_at'), 'team', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_updated_at'), 'team', ['updated_at'], unique=False)
    op.create_table('workqueue',
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workqueue_created_at'), 'workqueue', ['created_at'], unique=False)
    op.create_index(op.f('ix_workqueue_updated_at'), 'workqueue', ['updated_at'], unique=False)
    op.create_table('appointment',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=True),
    sa.Column('channel_origin', sa.String(length=24), nullable=True),
    sa.Column('requested_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('requested_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confirmed_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confirmed_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('location_name', sa.String(length=120), nullable=True),
    sa.Column('practitioner_name', sa.String(length=120), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('no_show_flag', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_created_at'), 'appointment', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointment_updated_at'), 'appointment', ['updated_at'], unique=False)
    op.create_table('consent',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('lawful_basis', sa.String(length=32), nullable=False),
    sa.Column('evidence_media_id', sa.Uuid(), nullable=True),
    sa.Column('effective_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_media_id'], ['mediaasset.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_created_at'), 'consent', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_updated_at'), 'consent', ['updated_at'], unique=False)
    op.create_table('conversation',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('current_owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_created_at'), 'conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_updated_at'), 'conversation', ['updated_at'], unique=False)
    op.create_table('externalaccountlink',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', 'subject', name='uq_external_subject')
    )
    op.create_index(op.f('ix_externalaccountlink_created_at'), 'externalaccountlink', ['created_at'], unique=False)
    op.create_index(op.f('ix_externalaccountlink_patient_id'), 'externalaccountlink', ['patient_id'], unique=False)
    op.create_index(op.f('ix_externalaccountlink_updated_at'), 'externalaccountlink', ['updated_at'], unique=False)
    op.create_table('patientaddress',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('use', sa.String(length=16), nullable=False),
    sa.Column('line1', sa.String(length=100), nullable=False),
    sa.Column('line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('geocode', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientaddress_created_at'), 'patientaddress', ['created_at'], unique=False)
    op.create_index(op.f('ix_patientaddress_patient_id'), 'patientaddress', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patientaddress_updated_at'), 'patientaddress', ['updated_at'], unique=False)
    op.create_table('patientcoverage',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('payer', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=120), nullable=True),
    sa.Column('member_id', sa.String(length=80), nullable=True),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.Column('period', sa.JSON(), nullable=True),
    sa.Column('relationship', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientcoverage_created_at'), 'patientcoverage', ['created_at'], unique=False)
    op.create_index(op.f('ix_patientcoverage_patient_id'), 'patientcoverage', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patientcoverage_updated_at'), 'patientcoverage', ['updated_at'], unique=False)
    op.create_table('patientidentifier',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'patient_id', 'system', 'value', name='uq_ident_unique')
    )
    op.create_index(op.f('ix_patientidentifier_created_at'), 'patientidentifier', ['created_at'], unique=False)
    op.create_index(op.f('ix_patientidentifier_patient_id'), 'patientidentifier', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patientidentifier_updated_at'), 'patientidentifier', ['updated_at'], unique=False)
    op.create_table('patientprofile',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex_at_birth', sa.String(length=32), nullable=True),
    sa.Column('gender_identity', sa.String(length=64), nullable=True),
    sa.Column('pronouns', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('interpreter_needed', sa.Boolean(), nullable=False),
    sa.Column('accessibility', sa.JSON(), nullable=True),
    sa.Column('contact_preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientprofile_created_at'), 'patientprofile', ['created_at'], unique=False)
    op.create_index(op.f('ix_patientprofile_patient_id'), 'patientprofile', ['patient_id'], unique=True)
    op.create_index(op.f('ix_patientprofile_updated_at'), 'patientprofile', ['updated_at'], unique=False)
    op.create_table('patientsdoh',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientsdoh_created_at'), 'patientsdoh', ['created_at'], unique=False)
    op.create_index(op.f('ix_patientsdoh_patient_id'), 'patientsdoh', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patientsdoh_updated_at'), 'patientsdoh', ['updated_at'], unique=False)
    op.create_table('patienttag',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patienttag_created_at'), 'patienttag', ['created_at'], unique=False)
    op.create_index(op.f('ix_patienttag_patient_id'), 'patienttag', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patienttag_updated_at'), 'patienttag', ['updated_at'], unique=False)
    op.create_table('practitionerschedule',
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitionerschedule_created_at'), 'practitionerschedule', ['created_at'], unique=False)
    op.create_index(op.f('ix_practitionerschedule_updated_at'), 'practitionerschedule', ['updated_at'], unique=False)
    op.create_table('teammember',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teammember_created_at'), 'teammember', ['created_at'], unique=False)
    op.create_index(op.f('ix_teammember_updated_at'), 'teammember', ['updated_at'], unique=False)
    op.create_table('textchunk',
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('locator', sa.JSON(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textchunk_created_at'), 'textchunk', ['created_at'], unique=False)
    op.create_index(op.f('ix_textchunk_updated_at'), 'textchunk', ['updated_at'], unique=False)
    op.create_table('waitlistentry',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=True),
    sa.Column('location_name', sa.String(length=120), nullable=True),
    sa.Column('practitioner_name', sa.String(length=120), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlistentry_created_at'), 'waitlistentry', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlistentry_updated_at'), 'waitlistentry', ['updated_at'], unique=False)
    op.create_table('checkinmeta',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('forms_completed', sa.JSON(), nullable=True),
    sa.Column('payment_collected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkinmeta_created_at'), 'checkinmeta', ['created_at'], unique=False)
    op.create_index(op.f('ix_checkinmeta_updated_at'), 'checkinmeta', ['updated_at'], unique=False)
    op.create_table('intakesession',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakesession_conversation_id'), 'intakesession', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_intakesession_created_at'), 'intakesession', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakesession_patient_id'), 'intakesession', ['patient_id'], unique=False)
    op.create_index(op.f('ix_intakesession_updated_at'), 'intakesession', ['updated_at'], unique=False)
    op.create_table('message',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['mediaasset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_updated_at'), 'message', ['updated_at'], unique=False)
    op.create_table('ticket',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary_auto', sa.Text(), nullable=True),
    sa.Column('summary_human', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_created_at'), 'ticket', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_updated_at'), 'ticket', ['updated_at'], unique=False)
    op.create_table('assignment',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_created_at'), 'assignment', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignment_updated_at'), 'assignment', ['updated_at'], unique=False)
    op.create_table('availabilityhold',
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('intake_session_id', sa.Uuid(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intakesession.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilityhold_created_at'), 'availabilityhold', ['created_at'], unique=False)
    op.create_index(op.f('ix_availabilityhold_token'), 'availabilityhold', ['token'], unique=True)
    op.create_index(op.f('ix_availabilityhold_updated_at'), 'availabilityhold', ['updated_at'], unique=False)
    op.create_table('intakeallergy',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('client_item_id', sa.String(length=64), nullable=True),
    sa.Column('substance', sa.String(length=120), nullable=False),
    sa.Column('reaction', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakeallergy_created_at'), 'intakeallergy', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakeallergy_session_id'), 'intakeallergy', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakeallergy_updated_at'), 'intakeallergy', ['updated_at'], unique=False)
    op.create_table('intakechiefcomplaint',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('codes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakechiefcomplaint_created_at'), 'intakechiefcomplaint', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakechiefcomplaint_session_id'), 'intakechiefcomplaint', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakechiefcomplaint_updated_at'), 'intakechiefcomplaint', ['updated_at'], unique=False)
    op.create_table('intakeconditionhistory',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('client_item_id', sa.String(length=64), nullable=True),
    sa.Column('condition', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('year_or_age', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakeconditionhistory_created_at'), 'intakeconditionhistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakeconditionhistory_session_id'), 'intakeconditionhistory', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakeconditionhistory_updated_at'), 'intakeconditionhistory', ['updated_at'], unique=False)
    op.create_table('intakefamilyhistory',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('client_item_id', sa.String(length=64), nullable=True),
    sa.Column('relative', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=160), nullable=False),
    sa.Column('age_of_onset', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakefamilyhistory_created_at'), 'intakefamilyhistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakefamilyhistory_session_id'), 'intakefamilyhistory', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakefamilyhistory_updated_at'), 'intakefamilyhistory', ['updated_at'], unique=False)
    op.create_table('intakemedication',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('client_item_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose', sa.String(length=120), nullable=True),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('adherence', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakemedication_created_at'), 'intakemedication', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakemedication_session_id'), 'intakemedication', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakemedication_updated_at'), 'intakemedication', ['updated_at'], unique=False)
    op.create_table('intakenote',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakenote_created_at'), 'intakenote', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakenote_session_id'), 'intakenote', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakenote_updated_at'), 'intakenote', ['updated_at'], unique=False)
    op.create_table('intakesocialhistory',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakesocialhistory_created_at'), 'intakesocialhistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakesocialhistory_session_id'), 'intakesocialhistory', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakesocialhistory_updated_at'), 'intakesocialhistory', ['updated_at'], unique=False)
    op.create_table('intakesummary',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakesummary_created_at'), 'intakesummary', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakesummary_session_id'), 'intakesummary', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakesummary_updated_at'), 'intakesummary', ['updated_at'], unique=False)
    op.create_table('intakesymptom',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('client_item_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.JSON(), nullable=True),
    sa.Column('onset', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=32), nullable=True),
    sa.Column('laterality', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['intakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakesymptom_created_at'), 'intakesymptom', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakesymptom_session_id'), 'intakesymptom', ['session_id'], unique=False)
    op.create_index(op.f('ix_intakesymptom_updated_at'), 'intakesymptom', ['updated_at'], unique=False)
    op.create_table('slaapplication',
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('paused_total_seconds', sa.Integer(), nullable=False),
    sa.Column('pause_started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('due_response_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('due_resolution_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('breach_state', sa.String(length=16), nullable=False),
    sa.Column('last_recalc_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['slapolicy.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slaapplication_created_at'), 'slaapplication', ['created_at'], unique=False)
    op.create_index(op.f('ix_slaapplication_updated_at'), 'slaapplication', ['updated_at'], unique=False)
    op.create_table('task',
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_updated_at'), 'task', ['updated_at'], unique=False)
    op.create_table('ticketnote',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticketnote_created_at'), 'ticketnote', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticketnote_updated_at'), 'ticketnote', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketnote_updated_at'), table_name='ticketnote')
    op.drop_index(op.f('ix_ticketnote_created_at'), table_name='ticketnote')
    op.drop_table('ticketnote')
    op.drop_index(op.f('ix_task_updated_at'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_slaapplication_updated_at'), table_name='slaapplication')
    op.drop_index(op.f('ix_slaapplication_created_at'), table_name='slaapplication')
    op.drop_table('slaapplication')
    op.drop_index(op.f('ix_intakesymptom_updated_at'), table_name='intakesymptom')
    op.drop_index(op.f('ix_intakesymptom_session_id'), table_name='intakesymptom')
    op.drop_index(op.f('ix_intakesymptom_created_at'), table_name='intakesymptom')
    op.drop_table('intakesymptom')
    op.drop_index(op.f('ix_intakesummary_updated_at'), table_name='intakesummary')
    op.drop_index(op.f('ix_intakesummary_session_id'), table_name='intakesummary')
    op.drop_index(op.f('ix_intakesummary_created_at'), table_name='intakesummary')
    op.drop_table('intakesummary')
    op.drop_index(op.f('ix_intakesocialhistory_updated_at'), table_name='intakesocialhistory')
    op.drop_index(op.f('ix_intakesocialhistory_session_id'), table_name='intakesocialhistory')
    op.drop_index(op.f('ix_intakesocialhistory_created_at'), table_name='intakesocialhistory')
    op.drop_table('intakesocialhistory')
    op.drop_index(op.f('ix_intakenote_updated_at'), table_name='intakenote')
    op.drop_index(op.f('ix_intakenote_session_id'), table_name='intakenote')
    op.drop_index(op.f('ix_intakenote_created_at'), table_name='intakenote')
    op.drop_table('intakenote')
    op.drop_index(op.f('ix_intakemedication_updated_at'), table_name='intakemedication')
    op.drop_index(op.f('ix_intakemedication_session_id'), table_name='intakemedication')
    op.drop_index(op.f('ix_intakemedication_created_at'), table_name='intakemedication')
    op.drop_table('intakemedication')
    op.drop_index(op.f('ix_intakefamilyhistory_updated_at'), table_name='intakefamilyhistory')
    op.drop_index(op.f('ix_intakefamilyhistory_session_id'), table_name='intakefamilyhistory')
    op.drop_index(op.f('ix_intakefamilyhistory_created_at'), table_name='intakefamilyhistory')
    op.drop_table('intakefamilyhistory')
    op.drop_index(op.f('ix_intakeconditionhistory_updated_at'), table_name='intakeconditionhistory')
    op.drop_index(op.f('ix_intakeconditionhistory_session_id'), table_name='intakeconditionhistory')
    op.drop_index(op.f('ix_intakeconditionhistory_created_at'), table_name='intakeconditionhistory')
    op.drop_table('intakeconditionhistory')
    op.drop_index(op.f('ix_intakechiefcomplaint_updated_at'), table_name='intakechiefcomplaint')
    op.drop_index(op.f('ix_intakechiefcomplaint_session_id'), table_name='intakechiefcomplaint')
    op.drop_index(op.f('ix_intakechiefcomplaint_created_at'), table_name='intakechiefcomplaint')
    op.drop_table('intakechiefcomplaint')
    op.drop_index(op.f('ix_intakeallergy_updated_at'), table_name='intakeallergy')
    op.drop_index(op.f('ix_intakeallergy_session_id'), table_name='intakeallergy')
    op.drop_index(op.f('ix_intakeallergy_created_at'), table_name='intakeallergy')
    op.drop_table('intakeallergy')
    op.drop_index(op.f('ix_availabilityhold_updated_at'), table_name='availabilityhold')
    op.drop_index(op.f('ix_availabilityhold_token'), table_name='availabilityhold')
    op.drop_index(op.f('ix_availabilityhold_created_at'), table_name='availabilityhold')
    op.drop_table('availabilityhold')
    op.drop_index(op.f('ix_assignment_updated_at'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_created_at'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_ticket_updated_at'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_created_at'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_message_updated_at'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_intakesession_updated_at'), table_name='intakesession')
    op.drop_index(op.f('ix_intakesession_patient_id'), table_name='intakesession')
    op.drop_index(op.f('ix_intakesession_created_at'), table_name='intakesession')
    op.drop_index(op.f('ix_intakesession_conversation_id'), table_name='intakesession')
    op.drop_table('intakesession')
    op.drop_index(op.f('ix_checkinmeta_updated_at'), table_name='checkinmeta')
    op.drop_index(op.f('ix_checkinmeta_created_at'), table_name='checkinmeta')
    op.drop_table('checkinmeta')
    op.drop_index(op.f('ix_waitlistentry_updated_at'), table_name='waitlistentry')
    op.drop_index(op.f('ix_waitlistentry_created_at'), table_name='waitlistentry')
    op.drop_table('waitlistentry')
    op.drop_index(op.f('ix_textchunk_updated_at'), table_name='textchunk')
    op.drop_index(op.f('ix_textchunk_created_at'), table_name='textchunk')
    op.drop_table('textchunk')
    op.drop_index(op.f('ix_teammember_updated_at'), table_name='teammember')
    op.drop_index(op.f('ix_teammember_created_at'), table_name='teammember')
    op.drop_table('teammember')
    op.drop_index(op.f('ix_practitionerschedule_updated_at'), table_name='practitionerschedule')
    op.drop_index(op.f('ix_practitionerschedule_created_at'), table_name='practitionerschedule')
    op.drop_table('practitionerschedule')
    op.drop_index(op.f('ix_patienttag_updated_at'), table_name='patienttag')
    op.drop_index(op.f('ix_patienttag_patient_id'), table_name='patienttag')
    op.drop_index(op.f('ix_patienttag_created_at'), table_name='patienttag')
    op.drop_table('patienttag')
    op.drop_index(op.f('ix_patientsdoh_updated_at'), table_name='patientsdoh')
    op.drop_index(op.f('ix_patientsdoh_patient_id'), table_name='patientsdoh')
    op.drop_index(op.f('ix_patientsdoh_created_at'), table_name='patientsdoh')
    op.drop_table('patientsdoh')
    op.drop_index(op.f('ix_patientprofile_updated_at'), table_name='patientprofile')
    op.drop_index(op.f('ix_patientprofile_patient_id'), table_name='patientprofile')
    op.drop_index(op.f('ix_patientprofile_created_at'), table_name='patientprofile')
    op.drop_table('patientprofile')
    op.drop_index(op.f('ix_patientidentifier_updated_at'), table_name='patientidentifier')
    op.drop_index(op.f('ix_patientidentifier_patient_id'), table_name='patientidentifier')
    op.drop_index(op.f('ix_patientidentifier_created_at'), table_name='patientidentifier')
    op.drop_table('patientidentifier')
    op.drop_index(op.f('ix_patientcoverage_updated_at'), table_name='patientcoverage')
    op.drop_index(op.f('ix_patientcoverage_patient_id'), table_name='patientcoverage')
    op.drop_index(op.f('ix_patientcoverage_created_at'), table_name='patientcoverage')
    op.drop_table('patientcoverage')
    op.drop_index(op.f('ix_patientaddress_updated_at'), table_name='patientaddress')
    op.drop_index(op.f('ix_patientaddress_patient_id'), table_name='patientaddress')
    op.drop_index(op.f('ix_patientaddress_created_at'), table_name='patientaddress')
    op.drop_table('patientaddress')
    op.drop_index(op.f('ix_externalaccountlink_updated_at'), table_name='externalaccountlink')
    op.drop_index(op.f('ix_externalaccountlink_patient_id'), table_name='externalaccountlink')
    op.drop_index(op.f('ix_externalaccountlink_created_at'), table_name='externalaccountlink')
    op.drop_table('externalaccountlink')
    op.drop_index(op.f('ix_conversation_updated_at'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_consent_updated_at'), table_name='consent')
    op.drop_index(op.f('ix_consent_created_at'), table_name='consent')
    op.drop_table('consent')
    op.drop_index(op.f('ix_appointment_updated_at'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_created_at'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_workqueue_updated_at'), table_name='workqueue')
    op.drop_index(op.f('ix_workqueue_created_at'), table_name='workqueue')
    op.drop_table('workqueue')
    op.drop_index(op.f('ix_team_updated_at'), table_name='team')
    op.drop_index(op.f('ix_team_created_at'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_slapolicy_updated_at'), table_name='slapolicy')
    op.drop_index(op.f('ix_slapolicy_created_at'), table_name='slapolicy')
    op.drop_table('slapolicy')
    op.drop_index(op.f('ix_routingrule_updated_at'), table_name='routingrule')
    op.drop_index(op.f('ix_routingrule_created_at'), table_name='routingrule')
    op.drop_table('routingrule')
    op.drop_index(op.f('ix_practitioner_updated_at'), table_name='practitioner')
    op.drop_index(op.f('ix_practitioner_name'), table_name='practitioner')
    op.drop_index(op.f('ix_practitioner_created_at'), table_name='practitioner')
    op.drop_table('practitioner')
    op.drop_index(op.f('ix_patient_updated_at'), table_name='patient')
    op.drop_index(op.f('ix_patient_created_at'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_mediaasset_updated_at'), table_name='mediaasset')
    op.drop_index(op.f('ix_mediaasset_created_at'), table_name='mediaasset')
    op.drop_table('mediaasset')
    op.drop_index(op.f('ix_location_updated_at'), table_name='location')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_created_at'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_channel_updated_at'), table_name='channel')
    op.drop_index(op.f('ix_channel_created_at'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_auditevent_updated_at'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_created_at'), table_name='auditevent')
    op.drop_table('auditevent')
    # ### end Alembic commands ###
