"""Add full practitioner details

Revision ID: 16712157a5c7
Revises: 122788c37ac0
Create Date: 2025-09-29 03:20:09.112503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16712157a5c7'
down_revision: Union[str, None] = '122788c37ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioner', sa.Column('location_id', sa.Uuid(), nullable=True))
    op.add_column('practitioner', sa.Column('designation', sa.Text(), nullable=True))
    op.add_column('practitioner', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('practitioner', sa.Column('profile_url', sa.String(), nullable=True))
    op.add_column('practitioner', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('practitioner', sa.Column('area_of_expertise', sa.Text(), nullable=True))
    op.add_column('practitioner', sa.Column('awards_recognition', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'practitioner', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practitioner', type_='foreignkey')
    op.drop_column('practitioner', 'awards_recognition')
    op.drop_column('practitioner', 'area_of_expertise')
    op.drop_column('practitioner', 'overview')
    op.drop_column('practitioner', 'profile_url')
    op.drop_column('practitioner', 'qualifications')
    op.drop_column('practitioner', 'designation')
    op.drop_column('practitioner', 'location_id')
    # ### end Alembic commands ###
