"""add eventoutbox table

Revision ID: 5b5ff7275c09
Revises: 16712157a5c7
Create Date: 2025-10-06 08:13:33.549492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5ff7275c09'
down_revision: Union[str, None] = '16712157a5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('textchunk_embedding_idx', table_name='textchunk', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('textchunk_fts_idx', table_name='textchunk', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('textchunk_fts_idx', 'textchunk', [sa.text("to_tsvector('simple'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index('textchunk_embedding_idx', 'textchunk', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
