from typing import Protocol, runtime_checkable

@runtime_checkable
class ObjectStoragePort(Protocol):
    def presign_upload(self, key: str, content_type: str, expires_seconds: int = 900) -> dict: ...
    def presign_download(self, key: str, expires_seconds: int = 900) -> str: ...
    def put_bytes(self, key: str, data: bytes, content_type: str) -> None: ...
    def delete(self, key: str) -> None: ...
    def presign_post(self, key: str, expires_seconds: int = 600) -> dict: ...